### PR TITLE
Refactor checklists

### PR DESCRIPTION
**Pull request by xuanxu**
This PR removes all the code related with removing reviewer checklists from the Review body.

Ref: Should be deployed at the same time as openjournals/whedon-api#138

### CODE REVIEW

**Comment by danielskatz** [comment]
I find percentage complete to be very useful - do we need to remove it?

**Comment by arfon** [comment]
> I find percentage complete to be very useful - do we need to remove it?

Me too. Unfortunately the current implementation will break if we make this change 😞. So I guess the question is, would we rather keep the percentage complete information, or address the usability challenges of the repository invitation flow that reviewers have to go through.

**Comment by danielskatz** [comment]
there's no way to work around the change and still have this?

**Comment by xuanxu** [comment]
Closing as this PR is not needed anymore

**Pull request closed without merging**
