### PR TITLE
Create improvements.md

### PR DESCRIPTION
**Pull request by arfon**
:wave: @openjournals/joss-editors @openjournals/jose-editors @parrish - this is an attempt to document all of the major areas of work we'd like to address with the funding from the Sloan Foundation.

Please let me know if you think I've missed something.

I've also opened a [GitHub Project](https://github.com/orgs/openjournals/projects/1) to track all of the issues associated with this work.

### CODE REVIEW

**Comment by kyleniemeyer** [comment]
Looks like @mtparrish wasn't tagged correctly?

**Comment by arfon** [comment]
> Looks like @mtparrish wasn't tagged correctly?

Good catch. It's @parrish.

**Comment by parrish** [comment]
👋  Looks good to me!  The project may be private though.

**Comment by arfon** [comment]
> The project may be private though.

How do you mean @parrish?

**Comment by arfon** [comment]
Do you mean https://github.com/orgs/openjournals/projects/1 is private?

**Comment by parrish** [comment]
Yep, or I don't have access to view it.

**Comment by parrish** [comment]
Thanks!  👍

**Comment by arfon** [comment]
Ah, OK. I've just invited you to the @openjournals org which should give you access.

**Comment by arfon** [comment]
Superceded by #361

**Pull request closed without merging**
