### PR TITLE
Suspend submissions

### PR DESCRIPTION
**Pull request by arfon**
@openjournals/joss-editors - in response to the COVID-19 pandemic I propose we suspend submissions for at least 30 days. At this time I'd rather we all focused on looking after ourselves and our loved ones rather than editing papers.

This pull request implements a small change on the JOSS website that will prevent any new submissions being created.

Screen Shot 2020-03-12 at 8 23 48 PM

**What about existing submissions?**

For submissions already submitted I propose we handle these on a 'best efforts' basis, that is, if you feel able to, you're welcome to keep working on your papers, but please adjust your expectations accordingly for the responsiveness of authors and reviewers.

### CODE REVIEW

**Comment by danielskatz** [comment]
maybe instead of "JOSS editorial team", "all-volunteer JOSS editorial team"?  I'm not sure if that's better in explaining, or makes us look less professional than other journals, so it's just a possible thought

**Comment by arfon** [comment]
@danielskatz - what about rephrasing the first sentence to be:

In light of the COVID-19 pandemic, and the fact that JOSS is a volunteer-run journal, the JOSS editorial team has taken the decision to suspend new submissions to JOSS for at 30 days (and possibly longer).

**Comment by kyleniemeyer** [comment]
LGTM!

**Comment by danielskatz** [comment]
Btw, happy belated birthday!

On Mar 13, 2020, at 18:04, Kyle Niemeyer <notifications@github.com> wrote:

﻿

LGTM!

**Comment by kyleniemeyer** [comment]
@danielskatz thanks!

**Pull request merged**
