### PR TITLE
changed submission links JOSS->JOSE

### PR DESCRIPTION
**Pull request by AoifeHughes**
Updates with respect to issue https://github.com/openjournals/joss/issues/1134

### CODE REVIEW

**Comment by danielskatz** [comment]
I don't understand why this *JOSS* page should point to JOSE instead of JOSS. Perhaps you meant to make this change in https://github.com/openjournals/jose ?  Or maybe I'm missing something?

**Comment by AoifeHughes** [comment]
Perhaps I misunderstand but JOSE is just a branch of this JOSS repo, if I've done the PR correctly then it applies directly to JOSE branch.

**Comment by danielskatz** [comment]
I see - I missed that this was in a branch.

**Comment by AoifeHughes** [comment]
No worries. I'm also no well-versed in ruby, I assumed it's just this one template file which needs the fix. So would feel more comfortable if someone else can sign off on this / push the big green merge button.

**Comment by arfon** [comment]
:+1: thanks @AoifeHughes. I've not deployed the JOSE app for a while so will wait until the morning before attempting this :-)

**Comment by arfon** [comment]
Deployed!

**Pull request merged**
