### PR TITLE
clarifying who is responsible

### PR DESCRIPTION
**Pull request by danielskatz**
intended to address https://github.com/openjournals/joss/issues/974
@khinsen - what do you think?

### CODE REVIEW

**Comment by kthyng** [comment]
This looks good to me.

**Review by kyleniemeyer — APPROVED** [review]

**Comment by khinsen** [comment]
Looks good to me!

**Comment by danielskatz** [comment]
given the approvals so far, @arfon, if you are ok with this, go ahead and merge it

**Comment by arfon** [comment]
:+1: thanks for raising this @khinsen and @danielskatz for the PR ✨

**Pull request merged**
