### PR TITLE
Adding words about not opening issues from checklist

### PR DESCRIPTION
**Pull request by arfon**
Related to https://github.com/openjournals/whedon-api/pull/133

### CODE REVIEW

**Comment by danielskatz** [comment]
I can't quite tell how "on the ..." is going to look - does "the" fit here?  Should we add "manually"?

**Comment by arfon** [comment]
Sorry, it will read:

> Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review on the software repository. 

Where _software repository_ links to the repository of the submission.

**Comment by danielskatz** [comment]
Maybe "in the software repository associated with the submission", where "software repository associated with the submission" is linked to the repo?

**Comment by danielskatz** [comment]
in vs on might be a US/UK English thing...

**Comment by danielskatz** [comment]
like how in most of the US, people wait "in line" except in NY where they wait "on line"

**Comment by arfon** [comment]
> in vs on might be a US/UK English thing...

I think it might. But I don't feel very strongly so have adopted your suggestions in da3265b7d34478c9f43df89448adb680d9bbb104.

**Pull request merged**
