### PR TITLE
Rails 6

### PR DESCRIPTION
**Pull request by xuanxu**
Rails 6!
The specs all pass but there's now two new `ActionView` deprecation warnings I don't know how to remove.
I have not manually checked every page/interaction, and didn't try the production environment so a 'staging' deploy and more eyes to test would be nice.

### CODE REVIEW

**Comment by arfon** [comment]
So awesome @xuanxu! Thanks for doing this. 

I've tried to deploy this as a separate app on Heroku and am getting this build failure, any ideas what the fix might be?

```
     Compiling…
       Compilation failed:
       error Couldn't find a package.json file in "/tmp/build_9f423493a6db9423487b7837fc79187a"

 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

Also, if it would be easier to add you as a collaborator on the Heroku app to debug this yourself just let me know.

**Comment by xuanxu** [comment]
Ouch, I activated `Webpacker` because it's the default JS compiler for Rails 6, but I didn't migrate all the javascript files so it fails when trying to compile. I think that's a different beast, so I've just removed Webpacker to keep using `Sprockets`.  Moving from the old asset pipeline to the new default can be done later. 

Deployment should work after this last commit :crossed_fingers:

**Comment by xuanxu** [comment]
References for future migration to Webpacker:
https://medium.com/michelada-io/from-the-asset-pipeline-to-webpack-ce5a4bc323a9
https://www.youtube.com/watch?v=Hz8d6zPDSrk
https://makandracards.com/makandra/69135-migration-from-the-asset-pipeline-to-webpacker

**Comment by arfon** [comment]
OK, deployed at https://joss-rails6.herokuapp.com

I'll have a click around later.

**Comment by arfon** [comment]
One issue I've spotted: The 'active' view looks awry: https://joss-rails6.herokuapp.com/papers/active i.e. there should be 104 papers, but only two get rendered...

**Comment by xuanxu** [comment]
No Rails 6 related, it’s also happening in master: https://joss.theoj.org/papers/active

**Comment by arfon** [comment]
This is currently deployed to production (https://joss.theoj.org) - I'm going to see how we get on there for a day or two before merging.

**Comment by xuanxu** [comment]
I've just added a couple commits to remove the deprecation warnings

**Comment by arfon** [comment]
This is looking ✨in production. Thanks again @xuanxu!

**Pull request merged**
