### PR TITLE
adding whedon generate pdf example to pre-review issue

### PR DESCRIPTION
**Pull request by danielskatz**

### CODE REVIEW

**Comment by arfon** [comment]
Good idea. Unfortunately this is in the wrong place - the edits you've made here are to some fixtures for the tests. I've added this language over in https://github.com/openjournals/whedon-api/commit/6611b88327b3dc0e19af97b12a6ee0a68b8ae90d

**Comment by danielskatz** [comment]
thanks - the source tree is extremely confusing to me, so I just grep for what I want to change and then change it - maybe I should have paid more attention to multiple results :)

**Comment by arfon** [comment]
> thanks - the source tree is extremely confusing to me, so I just grep for what I want to change and then change it - maybe I should have paid more attention to multiple results :)

Totally reasonable strategy :-)

**Comment by danielskatz** [comment]
although in this case, where the change I needed to make was in a different repo, I don't think I could have been successful

**Pull request closed without merging**
