### PR TITLE
Add 'donate' links and badges

### PR DESCRIPTION
**Pull request by xuanxu**
This PR adds "donate" links to the site's `About` page and to the repo's `README` page.

Re: #623

### CODE REVIEW

**Comment by danielskatz** [comment]
The title is a bit misleading - I think this is for JOSS's page, not NumFOCUS's.  Otherwise, this looks reasonable, though it's a bit hard to see without actually being in context in the live (or a test) site.

**Comment by xuanxu** [comment]
Here's a screenshot, the PR just adds a link and a badge to the cost section:

Before:
before

After:
after

**Comment by danielskatz** [comment]
that looks good, thanks.

Could we also create a donate word, button, or link in the right side "TOC" in the about page?

**Comment by danielskatz** [comment]
@arfon - can you merge this one too, since I think it's much more likely that this is where potential donors will come, rather than to the github page

**Pull request merged**
