### PR TITLE
Add co-publication guidelines to docs

### PR DESCRIPTION
**Pull request by kbarnhart**
Related to #819.

### CODE REVIEW

**Comment by danielskatz** [comment]
This seems to be in the review section of the docs, rather than the submission section - is this correct?

**Comment by danielskatz** [comment]
Do we also want something here for reviewers that says what they should be looking for?  Is this part of one of our existing review criteria, perhaps significant scholarly content?

**Comment by kbarnhart** [comment]
@danielskatz you are correct about the wrong place (should be fixed now). 🤦 

Not sure what I think about whether something should also be in the reviewer document. Will think on it.

**Comment by arfon** [comment]
Thanks for doing this @kbarnhart.

> Do we also want something here for reviewers that says what they should be looking for? Is this part of one of our existing review criteria, perhaps significant scholarly content?

Our currently language is as follows:

> - [ ] Substantial scholarly effort: Does this submission meet the scope eligibility described in the JOSS guidelines

Perhaps we could change this to _Unique and substantial scholarly effort_:

> - [ ] Unique and substantial scholarly effort: Does this submission meet the scope eligibility described in the JOSS guidelines.

**Comment by danielskatz** [comment]
@kbarnhart - I'm not sure how to change your suggested text, but I would prefer it if we could say something about what we would find problematic.

**Comment by danielskatz** [comment]
@arfon - Your suggestions seems good to me

**Comment by kbarnhart** [comment]
Agree that I like @arfon's suggestion. 

@danielskatz I think you should be able to edit the text via providing a review with suggestions. 

If that doesn't work, I just added you as a collaborator so you should now have push access to the branch.

**Comment by danielskatz** [comment]
@kbarnhart - as I wrote "I'm not sure how to change your suggested text"...

**Comment by kbarnhart** [comment]
@danielskatz, sorry if I'm being really dense today, do you mean that you don't know how you would like to change the content to add something about what would be problematic, or do you mean you are being blocked from modifying it. 

I had though the latter... 

I agree with you that adding that sort of element would be beneficial. Will think on it too.

**Comment by danielskatz** [comment]
I meant I don't know what words to add

**Review by arfon — APPROVED** [review]

**Pull request merged**
