### PR TITLE
Dashboard refresh

### PR DESCRIPTION
**Pull request by arfon**
:wave: @openjournals/joss-editors @openjournals/joss-eics 

This PR brings the editor dashboard and summary screens up to date with the latest site designs. It also adds a little extra information to the dashboard views for each editor:

dashboard

The new information available is as follows:

- Number of papers published in the last month that you edited.
- A rolling 3-month average for the number of papers being published per month edited by you.
- A rolling 3-month average for the number of papers being published per editor per month across all of JOSS.

Obviously for newer editors, these numbers may be zeroes, especially as papers take some time to process 😄.

Please let me know if you find any weird quirks with these numbers or if you have suggestions for more informative metrics. I think I did my maths correctly here 🤞

### CODE REVIEW

**Comment by labarba** [comment]
I'm a little worried that comparing the immediate-past 3-month rolling average for the editor, with the all-time monthly average for all editors, may send the wrong signals. The load on editors has changed over time, no? Why not use the same time periods for these two averages? (And 3 month could be too little: maybe 6?)

**Comment by arfon** [comment]
Sorry, just to be clear, both of these numbers are monthly averages across the last three months.

- The per-editor number (middle column) is the number of papers per month, averaged over a three month period. So in my case, 9 papers have been published in JOSS over the last three months which makes my monthly average 3.0.
- The 'all JOSS' last metric is the number of papers per month per editor across the whole of JOSS _in the last three months_ too. So the time periods are actually the same.

Does that make more sense?

**Comment by oliviaguest** [comment]
Sorry if this is the wrong place to ask, but is there a way to see all papers I have edited (not just ones that have not been accepted yet)? 😅

**Comment by labarba** [comment]
@oliviaguest Go to any published paper you edited, and look at "Editor" on the right-hand side, there's an "all papers" link.

**Pull request merged**
