### PR TITLE
Search

### PR DESCRIPTION
**Pull request by arfon**
This is a WIP PR that I'm going to keep deploying as I go to add search functionality to JOSS.

Features added/planned:
- [x] Basic filtering-by-language in the form of clickable 
- [x] Search by author
- [ ] Search by reviewer
- [x] Search by author-specific tags
- [ ] Search by paper body

### CODE REVIEW

**Comment by marcpaga** [comment]
Filtering by language does not work properly with `R`. 
Going to: [https://joss.theoj.org/papers/in/R](https://joss.theoj.org/papers/in/R) still shows non `R` publications. 
But it works with other languages such as `python` or `matlab`.

**Comment by arfon** [comment]
Thanks for spotting this @marcpaga. This should be fixed in https://github.com/openjournals/joss/pull/575/commits/fcac2bc083138c8ff7aeb9200d368b2c8f6f033a

**Comment by arfon** [comment]
OK, looks like searching the full paper body is going to be a little tougher than expected so I'm going to merge this as-is at this point and revisit that at a later point.

To recap, it's now possible to search JOSS papers in the following way:

- By programming language e.g. https://joss.theoj.org/papers/in/Python
- By author e.g. https://joss.theoj.org/papers/by/Adina%20Wagner
- By author tag (these are clickable from the `paper#show` view) e.g. https://joss.theoj.org/papers/tagged/astronomy
- By year e.g. https://joss.theoj.org/papers/year/2019
- By volume (JOSS publishes 1 'volume' per year) e.g. https://joss.theoj.org/papers/volume/1
- By issue (JOSS publishes 1 'issue' per month) e.g. https://joss.theoj.org/papers/issue/38

**Comment by labarba** [comment]
https://twitter.com/LorenaABarba/status/1162344407774965761?s=20

**Pull request merged**
