### PR TITLE
Update FUNDING.yml

### PR DESCRIPTION
**Pull request by Dr-G**
add NumFOCUS github sponsors button (recurring donations only)

This feature is launching today at GitHub Universe!

cc @arfon

### CODE REVIEW

**Comment by danielskatz** [comment]
nice!

**Comment by arfon** [comment]
@Dr-G - do you know how this will affect the sponsors link?

**Comment by Dr-G** [comment]
Yes, it will add "NumFOCUS" -- see an example on the [pandas repo](https://github.com/pandas-dev/pandas)

**Comment by arfon** [comment]
Got it. Thanks!

**Pull request merged**
