### PR TITLE
Scope updates

### PR DESCRIPTION
**Pull request by arfon**
Adding submission scope section to site.

cc @openjournals/joss-eics @labarba

### CODE REVIEW

**Comment by danielskatz** [comment]
When I look at the files changed here, this doesn't make sense - it's just removing a lot of requirements and then changing the name from requirements to scope.  Is this part of something else I need to look at as well?

**Comment by arfon** [comment]
> When I look at the files changed here, this doesn't make sense - it's just removing a lot of requirements and then changing the name from requirements to scope. Is this part of something else I need to look at as well?

@danielskatz - I'm trying to address https://github.com/openjournals/joss/issues/582 in this pull request. @labarba's (very reasonable) feedback in https://github.com/openjournals/joss/issues/582 on [my first attempt to address this](https://github.com/openjournals/joss/commit/d26e02936aea1edca664f8197c1dedd489f0e94c) was that we don't really want to repeat the about page content here, rather, we want to make it clear what submissions are considered in scope for JOSS.

**Comment by danielskatz** [comment]
I see, this is a fix to a previous attempt, not a fix to the site as it was - that's what was confusing me.  Go ahead and merge from my point of view, though I might make a small suggestion for a further tweak afterwards

**Comment by danielskatz** [comment]
Well, on second thought, I like some of the stuff that's there now, before the PR is merged.  Can we keep:

- The software should be open source as per the OSI definition.
- The software should have an obvious research application.
- The software should be feature-complete (no half-baked solutions) and designed for maintainable extension (not one-off modifications). Minor ‘utility’ packages, including ‘thin’ API clients, are not acceptable.

there.

And I think the part that now says
👀Learn more about the JOSS submission process ⟶
should really say
👀Full details about JOSS submission requirements and the JOSS submission process ⟶

**Comment by danielskatz** [comment]
Also maybe move the bullets under the text paragraph?

So, how about:

> **Scope & submission requirements:**
> 
> JOSS publishes articles about research software. This definition includes software that: solves complex modeling problems in a scientific context (physics, mathematics, biology, medicine, social science, neuroscience, engineering); supports the functioning of research instruments or the execution of research experiments; extracts knowledge from large data sets; offers a mathematical library, or similar.
> 
> JOSS submissions must:
> 
> - Be open source (having an [OSD-compliant license](https://opensource.org/licenses))
> - Have an obvious research application
> - Be feature-complete (no half-baked solutions) and be designed for maintainable extension (not one-off modifications)
> - Not be minor ‘utility’ packages, such as ‘thin’ API clients
> 
> 👀Full details about JOSS submission requirements and the JOSS submission process ⟶

We also might want to change the corresponding bullets in readthedocs to match, if we make changes to their language here

**Comment by arfon** [comment]
👍to those suggestions @danielskatz.

**Comment by arfon** [comment]
FYI, I deployed this PR so we could see how it looks live: https://joss.theoj.org/about#submitting

**Pull request merged**
