### PR TITLE
Stimulus + subject autocomplete

### PR DESCRIPTION
**Pull request by xuanxu**
- Turbo configured
- Stimulus configured
- Autocomplete added to the subject field in the new paper form

### CODE REVIEW

**Review by xuanxu — COMMENTED** [review]
This is the branch currenty deployed in the test env

**Comment by arfon** [comment]
I can't seem to log in on `test.joss.theoj.org` – is this the test env you're deploying to?

**Comment by xuanxu** [comment]
@arfon Yes, that's the test env. But migrating from turbolinks to Hotwire/Turbo broke the login button and I didn't notice it because I was already logged in. I have redeployed the branch and the orcid link should work now.

**Comment by xuanxu** [comment]
The purpose of this PR was to test separately the new Rails JS stack (Turbo+Stimulus) before continuing with the tracks feature. 
Everything seems OK => Merging it now into the `tracks` branch.

**Pull request merged**
