### PR TITLE
Updated submission guidelines

### LINKED ISSUE #294: Better guidelines for article content
In keeping with some recent ideas of having a "Guides" page (for authors, reviewers, and editors), rather than putting everything in the "About" page, I think it might be useful to include a bit more in the author guide, particularly for article content.

I don't think we should accept articles that only includes two or three sentences, or a single paragraph.  (The example on the "About" page is fairly short, which perhaps contributes to our more minimal submissions.) Submissions can be around a page and still require minimal effort to compile. 

If we want others to take JOSS articles seriously, then I think we (the editors) need to decide the minimum content needed for an article.

### PR DESCRIPTION
**Pull request by arfon**
👋 @openjournals/joss-editors. Please take a look at these changes to the submission criteria and improved guidelines for article content.

Fixes #294

### CODE REVIEW

**Comment by labarba** [comment]
Looks good to me.

**Comment by brainstorm** [comment]
I'm a bit uncertain on what constitutes a "minor utility packages"... for instance, [MultiQC](https://github.com/ewels/MultiQC) can be thought of "just a minor scaffold around other utilities/tools"... when in reality it's a quite substantial utility package.

**Comment by labarba** [comment]
@brainstorm : Like any guidance, it will have to be interpreted on a case-by-case basis, with editorial judgement.

**Comment by danielskatz** [comment]
> Just a stylistic pet peeve: instead of hyperlinking a superfluous word like "here," just hyperlink a relevant bit of text in a well-formed sentence.

+1

**Comment by danielskatz** [comment]
"JOSS welcomes submissions from broadly diverse research applications" could be "JOSS welcomes submissions from broadly diverse research areas"

**Comment by arfon** [comment]
> Do:
> please submit a pre-submission enquiry.

Good catch. Thanks @labarba

**Comment by karthik** [comment]
Changes look good to me (I was working with Arfon when we opened this PR).

**Pull request merged**
